### ISSUE TITLE
OpenQA.Selenium.WebDriverException : An unknown server-side error occurred while processing the command. Original error: disconnected: unable to send message to renderer (failed to check if window was closed: disconnected: not connected to DevTools) (Session info: chrome=117.0.5938.61)

### ISSUE THREAD

**Issue by aarif313** [aquality-automation/aquality-appium-mobile-dotnet-template#17]
Recently I have started facing this issue due to which multiple test cases are failing, below is the error I am getting

OpenQA.Selenium.WebDriverException : An unknown server-side error occurred while processing the command. Original error: disconnected: unable to send message to renderer
(failed to check if window was closed: disconnected: not connected to DevTools)
(Session info: chrome=117.0.5938.61)

This issue happens randomly because of which test case is failing.

**Comment by aarif313** [comment]
Additionally sometime fetch below issue as well,

"OpenQA.Selenium.WebDriverException : An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up"

**Comment by aarif313** [comment]
Can someone please help on this as this issue continues to happen.

**Comment by aarif313** [comment]
OpenQA.Selenium.WebDriverException : An unknown server-side error occurred while processing the command. Original error: disconnected: unable to send message to renderer
(failed to check if window was closed: disconnected: not connected to DevTools)
(Session info: chrome=117.0.5938.61)

**Comment by mialeska** [comment]
Hi @aarif313, thank you for reaching out. 
Usually the main cause of this error (disconnected: not connected to DevTools) is the mismatch between chrome version and chromedriver version. As for me, the version of chrome is 118. But I see chrome=117 in your error log, which is not a Latest version. So you should be using a proper verion in your settings.json configuration for Chrome.
Please check it out: it should not be 
> "webDriverVersion": "Latest",
it should be:
> "webDriverVersion": "MatchingBrowser"
or the exact version number, like:
>"webDriverVersion": "117.0.5938.61"

The main idea of "MatchingBrowser" strategy is to check the installed version of browser on the machine where the code is executed; it would not work properly when you run with `  "isRemote": true,` (e.g. against Selenium Grid, BrowserStack) if the version on the remote server differs from your local one.

**Comment by mialeska** [comment]
Closing this one as not related to Appium Mobile library.
