### ISSUE TITLE
Queries on Automation Testing with Aquality.Appium: Seeking Resolution

### ISSUE THREAD

**Issue by aarif313** [aquality-automation/aquality-appium-mobile-dotnet-template#18]
I have some queries with respect to automation listing as follows, kindly reply to this email,

•	CAPTCHA Automation
There is an application which is currently I am testing using Aquality, In that application for user registration there is a CAPTCHA mechanism which needs to be completed to complete registration.
Is there any way to automate CAPTCHA using Aquality.Appium/Aquality.Selenium or any other way you can suggest?

Please check below screenshot,

![image](https://github.com/aquality-automation/aquality-appium-mobile-dotnet-template/assets/108671033/7074ff04-9534-4ab8-a304-ceb2c9354e7a)

 

•	Showing Google Prompt while logging in through Google:
While testing a mobile application, I came across a scenario where I need to sign in using google, While signing in using google, after entering email and password when I click on login button, I see below screen, any way to bypass this ?

Please check below screenshots,

Sometime this Screen

![image](https://github.com/aquality-automation/aquality-appium-mobile-dotnet-template/assets/108671033/0d06d3c0-e5a4-461e-91c7-9faf151fc93f)

Sometime this Screen

![image](https://github.com/aquality-automation/aquality-appium-mobile-dotnet-template/assets/108671033/603b9c68-f97b-4e43-88e2-dcdd9901453f)

•	Uploading File in iOS App:
While testing a mobile application, I came across a scenario where I need to upload file in application which is under test, I am able to upload file in Android but not able to upload in iOS, Below is code I am using for Android. Could you please suggest a solution for iOS?

[When(@"I choose '([^']*)' file from file explorer")]
        public void WhenIChooseFileFromFileExplorer(FileItem fileItem)
        {
            if (AqualityServices.Application.PlatformName == PlatformName.Android)
            {
                fileExplorer.ClickListingModeButton();
                fileExplorer.ClickUploadItem(fileItem);
            }
            else
            {
                throw new Exception("NOT IMPLEMENTED for iOS");
           }            
   }

[When(@"I push '([^']*)' file")]
        public void WhenIPushFile(FileItem fileItem)
        {
            var filePathOnDevice = AqualityServices.Application.PlatformName == PlatformName.Android
            ? Path.Combine(DevicePath.AndroidPath.Humanize(), fileItem.GetFileName())
            : Path.Combine("", fileItem.GetFileName());
            var uploadedFilePath = fileItem.GetPathToTheFile();
            AqualityServices.Application.Driver.PushFile(filePathOnDevice, new FileInfo(uploadedFilePath));
        }

**Comment by mialeska** [comment]
Hi @aarif313 ! 
Although these questions are not necessarily related to Aquality.Appium library, I will try to help you with them.

1. Regarding the CAPTCHA, it was designed to avoid completing by robots. I believe that proper way of testing would be to contact developers and ask them to setup special captcha keys on test environments that would always be accepted, more details here: https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha.-what-should-i-do

2. Regarding the Google Prompt on sign in, please try to manage it with your google account settings. 
First of all, you can try to turn off 2-step verification as described here: https://support.google.com/accounts/answer/1064203?hl=en&co=GENIE.Platform%3DDesktop# 
Alternatively or if this will not work for you, you can set up a 2-step of verification that you will be able to automate. For example, you can set up an one-time password (OTP) e.g. Authenticator, and then just generate this time-based codes in your C# solution, using the library Otp.NET. Here is the guide: https://dev.to/j_sakamoto/selenium-testing---how-to-sign-in-to-two-factor-authentication-2joi

3. PushFile should be working for iOS as well, but it have some specifics. Please check out an article about them from official Appium site: https://appium.github.io/appium-xcuitest-driver/5.9/ios-xctest-file-movement/
